name: Check

on:
  pull_request:
    branches:
      - master

jobs:
  checkout:
    name: 'Check'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Packages
        uses: CultureHQ/actions-yarn@master
        with:
          args: install

      - name: Run Eslint
        uses: CultureHQ/actions-yarn@master
        with:
          args: lint

      - name: Run Stylelint
        uses: CultureHQ/actions-yarn@master
        with:
          args: style-check

      - name: Run Unit Tests
        uses: CultureHQ/actions-yarn@master
        with:
          args: test
